name: PowerShell Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $results = @()

          $results += Invoke-ScriptAnalyzer -Path .\PSMultiPass\PSMultiPass.psm1 -Severity Error
          $results += Invoke-ScriptAnalyzer -Path .\PSMultiPass\functions -Recurse -Severity Error

          if ($results) {
            $results | Format-Table
            Throw "PSScriptAnalyzer FAILED" # Fail the build if errors are found
          } else {
            Write-Host "PSScriptAnalyzer PASSED" -ForegroundColor Green
          }